In [ ]:
# Data Profiling E-Commerce Behavior Dataset

## Dataset
eCommerce Behavior Data from Multi-Category Store

## Tujuan
Melakukan eksplorasi awal dataset besar menggunakan Polars Lazy API.

Analisis:
- ukuran dataset
- struktur kolom
- jumlah baris
- contoh data
- missing value

In [2]:
import polars as pl
import os

In [4]:
DATA_PATH = "../data/raw/2019-Nov.csv"

In [5]:
file_size = os.path.getsize(DATA_PATH)

print("Ukuran dataset:")
print(round(file_size / (1024**3), 2), "GB")

Ukuran dataset:
8.39 GB

In [6]:
df = pl.scan_csv(
    DATA_PATH
)

df

In [7]:
df.collect_schema()

Schema([('event_time', String),
        ('event_type', String),
        ('product_id', Int64),
        ('category_id', Int64),
        ('category_code', String),
        ('brand', String),
        ('price', Float64),
        ('user_id', Int64),
        ('user_session', String)])

In [8]:
row_count = df.select(
    pl.len()
).collect()

row_count

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 67501979 │
└──────────┘

In [12]:
df.head(5).collect()

shape: (5, 9)
┌──────────────┬────────────┬────────────┬─────────────────────┬───┬────────┬────────┬───────────┬─────────────────────┐
│ event_time   ┆ event_type ┆ product_id ┆ category_id         ┆ … ┆ brand  ┆ price  ┆ user_id   ┆ user_session        │
│ ---          ┆ ---        ┆ ---        ┆ ---                 ┆   ┆ ---    ┆ ---    ┆ ---       ┆ ---                 │
│ str          ┆ str        ┆ i64        ┆ i64                 ┆   ┆ str    ┆ f64    ┆ i64       ┆ str                 │
╞══════════════╪════════════╪════════════╪═════════════════════╪═══╪════════╪════════╪═══════════╪═════════════════════╡
│ 2019-11-01   ┆ view       ┆ 1003461    ┆ 2053013555631882655 ┆ … ┆ xiaomi ┆ 489.07 ┆ 520088904 ┆ 4d3b30da-a5e4-49df- │
│ 00:00:00 UTC ┆            ┆            ┆                     ┆   ┆        ┆        ┆           ┆ b1a8-ba5943…        │
│ 2019-11-01   ┆ view       ┆ 5000088    ┆ 2053013566100866035 ┆ … ┆ janome ┆ 293.65 ┆ 530496790 ┆ 8e5f4f83-366c-4f70- │
│ 00:00:00 UTC ┆            ┆            ┆                     ┆   ┆        ┆        ┆           ┆ 860e-ca7417…        │
│ 2019-11-01   ┆ view       ┆ 17302664   ┆ 2053013553853497655 ┆ … ┆ creed  ┆ 28.31  ┆ 561587266 ┆ 755422e7-9040-477b- │
│ 00:00:01 UTC ┆            ┆            ┆                     ┆   ┆        ┆        ┆           ┆ 9bd2-6a6e8f…        │
│ 2019-11-01   ┆ view       ┆ 3601530    ┆ 2053013563810775923 ┆ … ┆ lg     ┆ 712.87 ┆ 518085591 ┆ 3bfb58cd-7892-48cc- │
│ 00:00:01 UTC ┆            ┆            ┆                     ┆   ┆        ┆        ┆           ┆ 8020-2f17e6…        │
│ 2019-11-01   ┆ view       ┆ 1004775    ┆ 2053013555631882655 ┆ … ┆ xiaomi ┆ 183.27 ┆ 558856683 ┆ 313628f1-68b8-460d- │
│ 00:00:01 UTC ┆            ┆            ┆                     ┆   ┆        ┆        ┆           ┆ 84f6-cec7a8…        │
└──────────────┴────────────┴────────────┴─────────────────────┴───┴────────┴────────┴───────────┴─────────────────────┘

In [10]:
missing = df.select(
    [
        pl.col(col).null_count().alias(col)
        for col in df.collect_schema().names()
    ]
)

missing.collect()

shape: (1, 9)
┌────────────┬────────────┬────────────┬─────────────┬───┬─────────┬───────┬─────────┬──────────────┐
│ event_time ┆ event_type ┆ product_id ┆ category_id ┆ … ┆ brand   ┆ price ┆ user_id ┆ user_session │
│ ---        ┆ ---        ┆ ---        ┆ ---         ┆   ┆ ---     ┆ ---   ┆ ---     ┆ ---          │
│ u32        ┆ u32        ┆ u32        ┆ u32         ┆   ┆ u32     ┆ u32   ┆ u32     ┆ u32          │
╞════════════╪════════════╪════════════╪═════════════╪═══╪═════════╪═══════╪═════════╪══════════════╡
│ 0          ┆ 0          ┆ 0          ┆ 0           ┆ … ┆ 9218235 ┆ 0     ┆ 0       ┆ 10           │
└────────────┴────────────┴────────────┴─────────────┴───┴─────────┴───────┴─────────┴──────────────┘